on:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Golang with cache
        id: golang-with-cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Resolve dependencies
        run: go mod tidy
      - name: Build Golang
        run: go build -o build/server cmd/api/main.go
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
      - name: Save Golang cache
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.golang-with-cache.outputs.build-cache-path }}
            ${{ steps.golang-with-cache.outputs.module-cache-path }}
          key: ${{ steps.golang-with-cache.outputs.cache-key }}