on:
  workflow_call:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Golang with cache
        id: golang-with-cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Format
        run: |
          echo 1 > code
          (gofmt -w .; (echo $? > code)) | tee format.log
          exit $(cat code)
      - name: Archive formatting artifacts
        uses: actions/upload-artifact@v4
        with:
          name: format
          path: format.log