on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Golang with cache
        id: golang-with-cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Create directory
        run: mkdir -p logs && mkdir -p logs/lint
      - name: Lint
        run: |
          golangci-lint run --config golangci.yaml --timeout 10m0s --out-format checkstyle:report.xml &
          golangci-lint run --config golangci.yaml --timeout 10m0s --out-format github-actions
      - name: Archive lint artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lint
          path: report.xml