on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Set image name
        id: image_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ steps.image_name.outputs.lowercase }}
      - name: Delete old image if exists
        uses: chipkent/action-cleanup-package@v1.0.3
        continue-on-error: true
        with:
          github-org: mandarine-io
          package-name: backend
          tag: ${{ inputs.tag }}
          github-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build and Publish Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./deploy/images/app.Dockerfile
          platforms:
            - linux/amd64
            - linux/arm64
          push: true
          tags:
            - ghcr.io/${{ steps.image_name.outputs.lowercase }}:${{ inputs.tag }}
            - ghcr.io/${{ steps.image_name.outputs.lowercase }}:latest
          labels: ${{ steps.meta.outputs.labels }}