on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ACCESS_TOKEN:
        required: true
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          tag: ${{ inputs.tag }}
        run: |
          if [[ "$tag" =~ rc[0-9]+$ ]]; then
            echo "Creating prerelease for tag: $tag"
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                --generate-notes \
                --prerelease
          else
            echo "Creating release for tag: $tag"
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                --generate-notes
          fi